#!/bin/bash 
         COUNTER=0
         while [  $COUNTER -lt 1001 ]; do
             echo The counter is $COUNTER
	     curl -X POST -H 'Content-Type: application/json' -d "{"data":{"ndarray":[$(( ( RANDOM % 670 )  + 1 )),$(( ( RANDOM % 8438 )  + 1 ))]}}" http://localhost:8080/seldon/als-movielens-no-spark/api/v0.1/predictions &
             let COUNTER=COUNTER+1 
         done
